package mk.ukim.finki.wp.lab.service.impl;

import mk.ukim.finki.wp.lab.model.Chef;
import mk.ukim.finki.wp.lab.model.Dish;
import mk.ukim.finki.wp.lab.repository.ChefRepository;
import mk.ukim.finki.wp.lab.repository.DishRepository;
import mk.ukim.finki.wp.lab.service.DishService;
import org.springframework.stereotype.Service;

import java.util.List;
@Service
public class DishServiceImpl implements DishService {

    private final DishRepository dishRepository;
    private final ChefRepository chefRepository;

    public DishServiceImpl(DishRepository dishRepository, ChefRepository chefRepository) {
        this.dishRepository = dishRepository;
        this.chefRepository = chefRepository;
    }

    @Override
    public List<Dish> listDishes() {
        return dishRepository.findAll();
    }

    @Override
    public Dish findById(Long id) {
        return dishRepository.findById(id).orElseThrow();
    }

    @Override
    public Dish create( String name, String cuisine, int preparationTime, Long chefId) {
        Chef chef = chefRepository.findById(chefId).orElseThrow();
        //dish id is not taken in when saving the dish and is generated by the id
        if(name.isBlank() || cuisine.isBlank() || preparationTime <= 0) {
            throw new IllegalArgumentException("Invalid data");
        }
        return dishRepository.save(new Dish(name, cuisine, preparationTime, chef));
    }

    @Override
    public Dish update(Long id, String name, String cuisine, int preparationTime) {
        Dish dish = findById(id);
        if(name.isBlank() || cuisine.isBlank() || preparationTime <= 0) {
            throw new IllegalArgumentException("Invalid data");
        }
        dish.setName(name);
        dish.setCuisine(cuisine);
        dish.setPreparationTime(preparationTime);

        return dishRepository.save(dish);
    }

    @Override
    public Dish update(Dish dish) {
        return dishRepository.save(dish);
    }

    @Override
    public Dish update(Long id, String name, String cuisine, int preparationTime, Long chefId) {
        Dish dish = findById(id);
        if(name.isBlank() || cuisine.isBlank() || preparationTime <= 0) {
            throw new IllegalArgumentException("Invalid data");
        }
        Chef chef = chefRepository.findById(chefId).orElseThrow();
        dish.setName(name);
        dish.setCuisine(cuisine);
        dish.setPreparationTime(preparationTime);
        dish.setChef(chef);

        return dishRepository.save(dish);
    }

    @Override
    public void delete(Long id) {
        dishRepository.deleteById(id);
    }
}
