package mk.ukim.finki.wp.lab.service.impl;

import mk.ukim.finki.wp.lab.bootstrap.DataHolder;
import mk.ukim.finki.wp.lab.model.Dish;
import mk.ukim.finki.wp.lab.repository.DishRepository;
import mk.ukim.finki.wp.lab.service.DishService;
import org.springframework.stereotype.Service;

import java.util.List;
@Service
public class DishServiceImpl implements DishService {

    private final DishRepository dishRepository;

    public DishServiceImpl(DishRepository dishRepository) {
        this.dishRepository = dishRepository;
    }

    @Override
    public List<Dish> listDishes() {
        return dishRepository.findAll();
    }

    @Override
    public Dish findById(Long id) {
        return dishRepository.findById(id).orElseThrow();
    }

    @Override
    public Dish create( String name, String cuisine, int preparationTime) {
        //dish id is not taken in when saving the dish and is generated by the id
        if(name.isBlank() || cuisine.isBlank() || preparationTime <= 0) {
            throw new IllegalArgumentException("Invalid data");
        }
        Long id = ++DataHolder.dishLastId;
        return dishRepository.save(new Dish(id, name, cuisine, preparationTime));
    }

    @Override
    public Dish update(Long id, String name, String cuisine, int preparationTime) {
        Dish dish = findById(id);
        if(name.isBlank() || cuisine.isBlank() || preparationTime <= 0) {
            throw new IllegalArgumentException("Invalid data");
        }
        dish.setName(name);
        dish.setCuisine(cuisine);
        dish.setPreparationTime(preparationTime);

        return dishRepository.save(dish);
    }

    @Override
    public void delete(Long id) {
        dishRepository.deleteById(id);
    }
}
